# Generated by Django 4.1.13 on 2024-05-25 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipos_contratacion',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipos_empleado',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('tipo_relacion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.area')),
            ],
            options={
                'db_table': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
            options={
                'db_table': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(max_length=15)),
                ('id_decano', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decano_facultad', to='events.empleado')),
            ],
            options={
                'db_table': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categorias', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('asistentes', models.ManyToManyField(related_name='asistentes', to='events.usuario')),
                ('conferencistas', models.ManyToManyField(related_name='conferencistas', to='events.usuario')),
                ('facultades_organizadoras', models.ManyToManyField(to='events.facultad')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.lugar')),
                ('programa_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.programa')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.facultad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sede'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='lugar_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tipocontratacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tipoempleado'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pais')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.usuario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='cod_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.departamento'),
        ),
        migrations.AddField(
            model_name='area',
            name='codigo_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.facultad'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_coordinador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_area', to='events.empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('id_coordinador',)},
        ),
    ]
