# Generated by Django 5.0.6 on 2024-05-20 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'eventos_departamentos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'eventos_paises',
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eventos_tipos_contratacion',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eventos_tipos_empleado',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.departamento')),
            ],
            options={
                'db_table': 'eventos_ciudades',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('lugar_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
            options={
                'db_table': 'eventos_empleados',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(max_length=15)),
                ('id_decano', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decano_facultad', to='events.empleado')),
            ],
            options={
                'db_table': 'eventos_facultades',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.facultad'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('id_coordinador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_area', to='events.empleado')),
                ('codigo_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.facultad')),
            ],
            options={
                'db_table': 'eventos_areas',
                'unique_together': {('id_coordinador',)},
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='cod_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pais'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.area')),
            ],
            options={
                'db_table': 'eventos_programas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
            options={
                'db_table': 'eventos_sedes',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sede'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tipocontratacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tipoempleado'),
        ),
    ]
